include/aws/event-stream/event_stream.h

Recent `Wconversion` will break the code because of failure to convert from `size_t` to `uint32_t`.
https://github.com/awslabs/aws-c-event-stream/blob/920c4f385bb5b6139f69b06233ebf84d1515a4cc/source/event_stream.c#L407
This PR will define constants as `uint32_t` to fix that.

Fix conversion from size_t to uint32_t.

---

CMakeLists.txt
bin/CMakeLists.txt
bin/event_stream_pipe.c
bin/event_stream_write_test_case.c

*Issue #, if available:*
When building static library, CPP SDK and aws-c-common will switch flag /MD to /MT, aws-checksums and aws-c-event-streams should do the same thing, otherwise there will be linking warning of incompatible MSVCRTD library.

Switch /MT to /MD for dynamic lib and /MD to /MT for static lib on Windows

---

.clang-tidy
source/event_stream.c

assert -> AWS_ASSERT, removed assert.h includes, added clang-tidy rule

---

CMakeLists.txt
bin/CMakeLists.txt
cmake/aws-c-event-stream-config.cmake
tests/CMakeLists.txt

*Issue*
If use aws-c-event-stream as a git submodule of aws-crt-cpp, `CMAKE_PROJECT_NAME` will be `aws-crt-cpp`, instead of `aws-c-event-stream`.
1. Replace `CMAKE_PROJECT_NAME` with `PROJECT_NAME`
2. Use `aws_use_package()` to find dependencies: `aws-c-common` and `aws-checksums`

Use aws-c-event-stream as a git submodule of aws-crt-cpp

---

source/event_stream_rpc_client.c
tests/event_stream_rpc_client_connection_test.c
tests/event_stream_rpc_server_connection_test.c

We were seeing deadlock if one stream was activated from within the on_closed() callback of another stream. This was because we used a lock to protect `continuation_table` AND the on_closed() callback was automatically invoked when an entry was removed.
Solution is to remove the automatic action when entry removed from table. Instead we invoke the on_closed() callback after the lock is released.
I wrote a local test in Python to prove this was the cause of the crash, and that this fixes it. Yes, I should have added a test here in C, but time
couldn't run tests because I'd keep getting SOCKET_ADDRESS_IN_USE. Now tests pick random ports until they find one that's open.

Release lock before invoking callbacks

---

source/event_stream_rpc_client.c
source/event_stream_rpc_server.c
tests/event_stream_rpc_client_connection_test.c

Bug would manifest as a `AWS_ERROR_EVENT_STREAM_RPC_PROTOCOL_ERROR` if an `APPLICATION_MESSAGE` was sent immediately upon receiving a `CONNECT_ACK`
Turns out the client was setting `state=CONNECT_PROCESSED` in two places:
1) When writing the CONNECT message
2) When the CONNECT message's write-completion callback fired.
Fix is to ONLY set `state=CONNECT_PROCESSED` in place 1.
Bug would occur if the CONNECT_ACK was received before the CONNECT's write-complete callback fired. The state would go from CONNECT_ACK_PROCESSED back to CONNECT_PROCESSED.
This bug began manifesting when aws-c-io changed (PR# https://github.com/awslabs/aws-c-io/pull/353) so that the write-completion callback never fired synchronously. This made it possible to receive a CONNECT_ACK before the CONNECT's …

Fix bug where client "forgets" it received CONNECT_ACK

---

include/aws/event-stream/private/event_stream_rpc_priv.h

A semicolon slipped onto the end of the JSON bodies of some of the protocol error messages.  JSON deserializers barf on these messages.

Fix JSON in protocol error message body definitions

---

source/event_stream.c

Fix for deprecated header API always failing

---

source/event_stream_channel_handler.c

Fixes an issue where event stream ids could be sent in non-ascending order due to the the way the default channel task scheduling can change behavior based on whether or not it is invoked from the seated event loop thread.  This was considered a much easier and less risky change than doing a large refactoring to how event stream messages are submitted and serialized.
The problem came about when continuations were activated from both an external thread and the event loop thread (for example, on a stream callback).  It was possible that the external thread would allocate an id first and submit its task to flush the stream creation message, but then that task would get "leap-frogged" by an activation submitted on the event stream thread with a higher id.  By using an API that always uses the …

Use the serialized task scheduling method for submitting message tasks

---

source/event_stream_rpc_client.c

* Prevent in-flight data to a continuation that has been shut down from the client (and removed from the table) from shutting down the connection

Relax protocol constraint to work around client-side race condition

---

source/event_stream_rpc_client.c
tests/event_stream_rpc_client_connection_test.c
tests/event_stream_rpc_server_connection_test.c

* Hash elements are invalidated/mutated by add/remove.  If you're protecting your table with a lock, you must pull out your value from the element before releasing it.
* Some windows tests were flaky because Windows was giving a different error code on some port collisions

Fix continuation race condition and windows test failures

---

bin/event_stream_write_test_case.c

Issue: Today my Mac started issuing warnings about sprintf().
Changes: Use snprintf() instead.

sprintf() -> snprintf()

---

include/aws/event-stream/event_stream.h
source/event_stream.c
tests/message_streaming_decoder_test.c

- Adds a new onComplete callback to indicate a message is decoded successfully. 

Add onComplete callback for streaming decoder

---

source/event_stream_rpc_client.c

Ensure that the continuation completion callbacks and its decref only get performed once no matter what the situation
Greengrass has a high-level repro and the logs show the completion callback and the decref inside occuring twice for the same continuation, once due to terminate stream flags on the outbound client socket write callback and once due to terminate stream flags received in the meantime from the server's response.
I was not able to come up with a test with the existing framework that triggered this condition, however.
Solution uses an atomic because it's not clear we can guarantee that the completion callback always gets invoked on the event loop thread.

Double Terminate Crash

---

bin/CMakeLists.txt

- The `target_link_libraries` should be either all-keyworded or non-keyworded. For non-keyworded configurations, there is no default, and it can be either PUBLIC or PRIVATE, depending on various configurations. So, explicitly make it private.
Source: https://cmake.org/pipermail/cmake/2016-May/063400.html

Explicit Private for target_link_libraries

---

include/aws/event-stream/event_stream_rpc_client.h
include/aws/event-stream/event_stream_rpc_server.h
source/event_stream.c
source/event_stream_rpc_server.c
tests/event_stream_rpc_server_connection_test.c

Issue: https://github.com/awslabs/aws-c-io/issues/576

Change `port` from uint16_t to uint32_t, to support VSOCK

---

include/aws/event-stream/event_stream.h

**Issue #:**
https://github.com/awslabs/aws-c-common/issues/973
**Research:**
6 years ago, PR https://github.com/awslabs/aws-c-event-stream/pull/5 made these constants `uint32_t` via a cast.
**Description of changes:**
Avoid `-Wuseless-cast` warnings, don't cast `size_t` to `uint32_t` on 32-bit platforms.

Fix -Wuseless-cast compiler warning for public headers

---

bin/event_stream_write_test_case.c
source/event_stream.c

aws_base64_encode() no longer adds a "secret" null terminator after `.len`. See: https://github.com/awslabs/aws-c-common/pull/1188

Adapt to aws_base64_encode() no longer adding a null terminator

---

include/aws/event-stream/event_stream.h

After internal discussion, we have decided that clients should validate that the message size is at most 24MB.

Reduce Max Message Size to 24MB

---

include/aws/event-stream/event_stream_exports.h

*Issue #, if available:*
make AWS_CRT_USE_WINDOWS_DLL_SEMANTICS the variable for forcing win semantics
remove gcc < 4

make exports consistent

---

README.md

*Issue #, if available:*
The path to the diagram image is wrong in the README file. So, instead of the picture, there's just [404 icon](https://github.com/awslabs/aws-c-event-stream/blob/v0.5.4/README.md#encoding).
Fix the path.
The resulting README file can be found [here](https://github.com/awslabs/aws-c-event-stream/blob/772db62b1074f7e26f7911250265c7081d1d0efe/README.md)

Fix path for diagram in README

---

include/aws/event-stream/event_stream_rpc_client.h
source/event_stream_rpc_client.c
source/event_stream_rpc_server.c

* adds a termination callback for continuations.  This gives us a safe, guaranteed (regardless of state) timepoint after which we know no further callbacks are possible for binding object lifetime management.
* adds a termination callback for connections.  This gives us a safe, guaranteed (regardless of state) timepoint after which we know no further callbacks are possible for binding object lifetime management.
* relaxes the server-side constraint around stream id lookup for incoming messages.  A terminate-stream-flagged message with no corresponding continuation is no longer a protocol error in order to support simultaneous close.  This probably should have been done three years ago when https://github.com/awslabs/aws-c-event-stream/pull/83 was applied.
* Fixes a continuation table race …

Continuation termination callback support

---

source/event_stream_rpc_client.c
source/event_stream_rpc_server.c
tests/event_stream_rpc_client_connection_test.c

Issue: send_protocol_message directly accessed the channel/handler when there was no guarantee they would still be valid.
Solution: Remove the atomics and divided internal data into event-loop-only and lock-synchronized.  Updated public APIs to use event loop tasks if they need to access the channel.  This does mean that certain API calls that would fail synchronously now fail asynchronously.

Refactor client connection for thread safety
